terc:
  path: ./data/TERC_Urzedowy_2018-02-24.csv
  type:
    province: null
    city: miasto
mongo:
  host: localhost
  port: 27017
  collection:
    province:
      name: province
      drop: true
    city:
      name: city
      drop: true
  refresh: true