terc:
  path: ./data/TERC_Urzedowy_2018-02-24.csv
  type:
    province: województwo
    city: 
      regular: miasto
      capital: 
      county: miasto na prawach powiatu
    commune: 
      city: gmina miejska
      village: gmina wiejska
      city_village: gmina miejsko-wiejska
    county: powiat
    village: obszar wiejski
    district:
      regular: dzielnica
      delegacy: delegatura
      
    
mongo:
  host: localhost
  port: 27017
  collection:
    province:
      name: province
      drop: true
    city:
      name: city
      drop: true
  refresh: true